baseURL: https://impadalko.com/
languageCode: en-us
title: Impadalko
theme: "PaperMod"
menu:
  main:
    - name: Games
      pageRef: /games
      weight: 1
    - name: About
      pageRef: /about
      weight: 99
