baseURL: https://impadalko.com/
languageCode: en-us
title: Impadalko
theme: "PaperMod"
params:
  mainSections:
    - reflections
    - games
  homeInfoParams:
    Title: "Impadalko"
    Content: "Personal blog of Ivan Padalko. [Read more about me](/about)"
  socialIcons:
    - name: rss
      url: "/index.xml"
    - name: github
      url: "https://github.com/impadalko"
permalinks:
  reflections: "/reflections/:title/"
  games: "/games/:title/"
menu:
  main:
    - name: Games
      pageRef: /games
      weight: 1
    - name: Reflections
      pageRef: /reflections
      weight: 1
    - name: About
      pageRef: /about
      weight: 99
